#!/bin/bash

# Create a secret key for the django app
echo "export SECRET_KEY='$(openssl rand -hex 40)'" > ./.DJANGO_SECRET_KEY
source ./.DJANGO_SECRET_KEY


# check if the required packages are installed or not 
if [[ ! $(dpkg --get-selections | grep '^python3-pip.*install$') || ! $(dpkg --get-selections | grep '^virtualenv.*install$') || ! $(dpkg --get-selections | grep '^python-is-python3.*install$') ]]
then 
	sudo apt install python-is-python3 python3-pip virtualenv -y
fi

# check if the virtualenv is installed
if [ ! -d '~/env' ]
then 
	python -m virtualenv ~/env
fi

#sudo -i -u ubuntu bash << eof
#source ~/env/bin/activate
#pip install -r /home/ubuntu/everest/ramcov4/lookup/requirements
nohup python /home/ubuntu/everest/ramcov4/lookup/manage.py runserver 0.0.0.0:8000 &
#eof
